alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
  extraPorts:
    - name: "http"
      port: 4318
      targetPort: 4318
      protocol: "TCP"
    - name: "grpc"
      port: 4317
      targetPort: 4317
      protocol: "TCP"
