apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: lambda256
  labels:
    app: redis
spec:
  replicas: 1 # Redis 인스턴스 개수
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.0-alpine # 원하는 Redis 버전을 지정하세요
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
