apiVersion: v1
kind: Service
metadata:
  name: bullq-consumer-service
  namespace: lambda256
spec:
  type: ClusterIP
  selector:
    app: bullq-consumer
    ctx: otel101
  ports:
    - port: 80
      targetPort: 3000
