apiVersion: v1
kind: Service
metadata:
  name: otel101-mysql
  namespace: lambda256
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306 # 클러스터 내에서 노출할 포트
      targetPort: 3306 # MySQL 컨테이너의 포트
  type: ClusterIP # 클러스터 내부에서만 접근 가능

