apiVersion: v1
kind: Service
metadata:
  name: otel101-service
  namespace: lambda256
spec:
  type: ClusterIP 
  selector:
    app: otel101-api-server
    ctx: otel101
  ports:
    - port: 80
      targetPort: 3000
