apiVersion: v1
kind: Service
metadata:
  name: otel101-redis
  namespace: lambda256
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 # 서비스가 노출할 포트
      targetPort: 6379 # Redis 컨테이너의 포트
  type: ClusterIP # 기본적으로 클러스터 내에서 접근 가능
