// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: pb/otel-101.proto

package otel101

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ChargeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *ChargeResponse) Reset() {
	*x = ChargeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponse) ProtoMessage() {}

func (x *ChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponse.ProtoReflect.Descriptor instead.
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type DeliveryOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *DeliveryOrderRequest) Reset() {
	*x = DeliveryOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryOrderRequest) ProtoMessage() {}

func (x *DeliveryOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryOrderRequest.ProtoReflect.Descriptor instead.
func (*DeliveryOrderRequest) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeliveryOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *DeliveryOrderResponse) Reset() {
	*x = DeliveryOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryOrderResponse) ProtoMessage() {}

func (x *DeliveryOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryOrderResponse.ProtoReflect.Descriptor instead.
func (*DeliveryOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryOrderResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type DeliveryInquiryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *DeliveryInquiryRequest) Reset() {
	*x = DeliveryInquiryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryInquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInquiryRequest) ProtoMessage() {}

func (x *DeliveryInquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInquiryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryInquiryRequest) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryInquiryRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type DeliveryInquiryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeliveryInquiryResponse) Reset() {
	*x = DeliveryInquiryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_otel_101_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryInquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInquiryResponse) ProtoMessage() {}

func (x *DeliveryInquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_otel_101_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInquiryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryInquiryResponse) Descriptor() ([]byte, []int) {
	return file_pb_otel_101_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryInquiryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_pb_otel_101_proto protoreflect.FileDescriptor

var file_pb_otel_101_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x6f, 0x74, 0x65, 0x6c, 0x2d, 0x31, 0x30, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x22, 0x27, 0x0a, 0x0d,
	0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x30,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x38, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4d, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x43, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f,
	0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xbb, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x6f,
	0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6f, 0x74,
	0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79,
	0x12, 0x1f, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x31, 0x30, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x71, 0x75, 0x69, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x6e, 0x62, 0x30, 0x73, 0x2f, 0x6f, 0x74, 0x65, 0x6c, 0x2d,
	0x31, 0x30, 0x31, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x74, 0x65, 0x6c,
	0x31, 0x30, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_otel_101_proto_rawDescOnce sync.Once
	file_pb_otel_101_proto_rawDescData = file_pb_otel_101_proto_rawDesc
)

func file_pb_otel_101_proto_rawDescGZIP() []byte {
	file_pb_otel_101_proto_rawDescOnce.Do(func() {
		file_pb_otel_101_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_otel_101_proto_rawDescData)
	})
	return file_pb_otel_101_proto_rawDescData
}

var file_pb_otel_101_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_otel_101_proto_goTypes = []any{
	(*ChargeRequest)(nil),           // 0: otel101.ChargeRequest
	(*ChargeResponse)(nil),          // 1: otel101.ChargeResponse
	(*DeliveryOrderRequest)(nil),    // 2: otel101.DeliveryOrderRequest
	(*DeliveryOrderResponse)(nil),   // 3: otel101.DeliveryOrderResponse
	(*DeliveryInquiryRequest)(nil),  // 4: otel101.DeliveryInquiryRequest
	(*DeliveryInquiryResponse)(nil), // 5: otel101.DeliveryInquiryResponse
}
var file_pb_otel_101_proto_depIdxs = []int32{
	0, // 0: otel101.PaymentService.Charge:input_type -> otel101.ChargeRequest
	2, // 1: otel101.DeliveryService.DeliveryOrder:input_type -> otel101.DeliveryOrderRequest
	4, // 2: otel101.DeliveryService.DeliveryInquiry:input_type -> otel101.DeliveryInquiryRequest
	1, // 3: otel101.PaymentService.Charge:output_type -> otel101.ChargeResponse
	3, // 4: otel101.DeliveryService.DeliveryOrder:output_type -> otel101.DeliveryOrderResponse
	5, // 5: otel101.DeliveryService.DeliveryInquiry:output_type -> otel101.DeliveryInquiryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_otel_101_proto_init() }
func file_pb_otel_101_proto_init() {
	if File_pb_otel_101_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_otel_101_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChargeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_otel_101_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChargeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_otel_101_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_otel_101_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_otel_101_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryInquiryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_otel_101_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryInquiryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_otel_101_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_otel_101_proto_goTypes,
		DependencyIndexes: file_pb_otel_101_proto_depIdxs,
		MessageInfos:      file_pb_otel_101_proto_msgTypes,
	}.Build()
	File_pb_otel_101_proto = out.File
	file_pb_otel_101_proto_rawDesc = nil
	file_pb_otel_101_proto_goTypes = nil
	file_pb_otel_101_proto_depIdxs = nil
}
